### ISSUE TITLE
doc/_build/ does not need to be checked in

### ISSUE THREAD

**Issue by weikang9009** [pysal/spaghetti#133]
Readthedocs will generate the html files. So I think there is no need to check in the [doc/_build/](https://github.com/pysal/spaghetti/tree/master/doc/_build) folder

**Comment by jGaboardi** [comment]
@weikang9009 So I should delete the [/doc/_build](https://github.com/pysal/spaghetti/tree/master/doc/_build) folder? I thought that when I ran Readthedocs back in August it generated that whole directory automatically. I am not sure what I should change here.

**Comment by weikang9009** [comment]
Sorry for the confusion. If you run `make html` locally, the /doc/_build folder will be automatically generated. But we do not need to `git add, commit, & push` them to the github remote repo since [Readthedocs](https://readthedocs.org/) will read the conf.py and rst files inside doc/ and generate files identical to files in /doc/_build. Therefore, pushing the /doc/_build folder to the github remote seems to be redundant (and adding too many extra files).

**Comment by jGaboardi** [comment]
Ahhhh, ok! Thanks for the explanation! I’ll fix this before tomorrow.


On Oct 31, 2018, at 4:41 PM, Wei Kang <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry for the confusion. If you run make html locally, the /doc/_build folder will be automatically generated. But we do not need to git add, commit, & push them to the github remote repo since Readthedocs<https://urldefense.proofpoint.com/v2/url?u=https-3A__readthedocs.org_&d=DwMFaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=w0GmL-bHxKk-5ozcPrmZJkeb7kpZt1KvTEs71QYt-xw&m=DR5V-DmivXACZzAmaCKNOjNleTa-z75Sd8DPRLBg08s&s=S3TIEKGymJstUH-jZrGfDQQGSYrx_AQdGkpW60ovbaE&e=> will read the conf.py and rst files inside doc/ and generate files identical to files in /doc/_build. Therefore, pushing the /doc/_build folder to the github remote seems to be redundant (and adding too many extra files).

**Comment by jGaboardi** [comment]
Resolved in #134
