### ISSUE TITLE
spaghetti api docs rendering incorrectly

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#285]
The [`spaghetti`](https://pysal-spaghetti.readthedocs.io/en/latest/api.html) api docs rendering incorrectly. Unlike [`giddy`](https://giddy.readthedocs.io/en/latest/api.html) api docs that render left-justified, the [`spaghetti`](https://pysal-spaghetti.readthedocs.io/en/latest/api.html) api docs are centered. After reviewing the files in the [`doc`](https://github.com/pysal/spaghetti/tree/master/doc) directory, I could not find any obvious differences with `giddy`'s.

**Comment by jGaboardi** [comment]
@weikang9009, when you have a chance can you take a look at this?

**Comment by jGaboardi** [comment]
@sjsrey

**Comment by weikang9009** [comment]
I thought this might have sth to do with different python versions we were relying on to build the docs (giddy was using python 3.7 and spaghetti was using python 3.6). So I tried on changing python 3.6 to 3.6 for readthedocs building. But the tables of spaghetti docs were still center-aligned. 

Then I realized that spaghetti installed dependencies from conda-forge while giddy is relying on pip. There could be a version difference in `sphinx-bootstrap-theme`. It turns out that [the most updated version on pypi is 0.7.1](https://pypi.org/project/sphinx-bootstrap-theme/) while it is [0.6.4 on conda-forge](https://github.com/conda-forge/sphinx_bootstrap_theme-feedstock/blob/master/recipe/meta.yaml). The 0.7.1 version on conda-forge has a pr but never got merged.

**Comment by weikang9009** [comment]
In PR https://github.com/pysal/spaghetti/pull/286 I changed the style of the css file for a temporary fix. It renders fine on my fork https://spaghetti-wei.readthedocs.io/en/latest/api.html

**Comment by jGaboardi** [comment]
resolved by #286

**Comment by sjsrey** [comment]
When building the meta docs I'm getting some incomplete links now:

![Screenshot from 2019-06-16 12-32-22](https://user-images.githubusercontent.com/118042/59568681-e8340a80-9032-11e9-81bb-7221c49e4243.png)

**Comment by sjsrey** [comment]
@renanxcortes  and @weikang9009  added here as we have the same issue in building the segregation [docs](https://github.com/pysal/segregation/issues/58).

It would be great to figure out the solution one time and then post it in the submodule template, or somewhere central, where other maintainers can look.

**Comment by weikang9009** [comment]
I think it is because those functions are not properly specified. For instance, there is no `spaghetti.NetworkF`, but we should use `spaghetti.Network.NetworkF` instead.

I wonder why the spaghetti api for the meta package is different from the one on the  spaghetti docs website?

<img width="977" alt="image" src="https://user-images.githubusercontent.com/7359284/59568915-e4a28280-9036-11e9-8a22-fae09e142be1.png">

**Comment by sjsrey** [comment]
Did spaghetti change since the last meta release, because the meta api docs used to work:

https://pysal.readthedocs.io/en/latest/api.html

**Comment by sjsrey** [comment]
Fixed now.

**Comment by jGaboardi** [comment]
@sjsrey What was the actual issue? Was it because the `meta` included [`spaghetti v1.1.0`](https://github.com/pysal/pysal/blob/master/pysal/explore/spaghetti/__init__.py) but the current `spaghetti` version is [`1.3`](https://github.com/pysal/spaghetti/blob/master/spaghetti/__init__.py)?

**Comment by sjsrey** [comment]
Yes, that is essentially it.

Meta 2.0 was using v1.1.0 https://pysal.readthedocs.io/en/latest/api.html
while the planned 2.1 will use v1.3 https://pysal-spaghetti.readthedocs.io/en/latest/api.html

Will have to develop a method to catch these kinds of changes in the api.rst files from each subpackage between versions when doing  a new meta release.

**Comment by jGaboardi** [comment]
Shall I add this point to the July meeting agenda?

**Comment by sjsrey** [comment]
Sure, that'd be helpful.
