### ISSUE TITLE
mock c modules for doc dependencies

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#288]
Consider @renanxcortes's [method](https://github.com/pysal/segregation/issues/58#issuecomment-503368564) as an alternative to #268 for failing doc builds.

**Comment by renanxcortes** [comment]
So, I realized that I only needed to add `rtree` in the mock (https://github.com/pysal/segregation/pull/69/commits/b0f3252751692f624d0b5f56a238801acfcd6e4b), so currently this is the only package that is relying on this. I moved other sphinx dependencies to `requirements_docs.txt` and point `readthedocs.yml` to this requirements.

**Comment by weikang9009** [comment]
The mock solution could be useful in some context, but [the mechanism here is to mock all imports under the mocked package (`rtree` here)](http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports). If some doctests (inline docstrings) are actually using`rtree` functionalities, those python codes will not work. Since we have successfully used `conda` to install `rtree` for spaghetti, I would suggest stick to the current configuration for now.

**Comment by renanxcortes** [comment]
Yes, totally agree, if the docstring rely on the "mocked" modules (in this case `rtree`) the mock solution is may not be the best solution and definitely the current configuration is the best strategy.

I just wanted to point that I used the mock approach because I couldn't use the conda channel to build the readthedocs on sphinx. If we manage to figure out a way to overcome the issue that I was getting in this comment: https://github.com/pysal/segregation/issues/58#issuecomment-503236567 (spaghetti probably didn't face this issue), I think the best would be to use the conda channel for segregation.

**Comment by jGaboardi** [comment]
Closing this due to the switch to [GitHub hosted docs](https://github.com/pysal/spaghetti/pull/304)
