### ISSUE TITLE
improve spaghetti homepage and notebooks?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#332]
Referencing [this critique](https://gitter.im/pysal/pysal?at=5dd1dfd7e75b2d5a19efb7cc) from the `pysal` gitter channel.

Potential for improvement:
 * "quick-start" guide
 * thoroughly explain a basic workflow, while linking to other pysal submodules
 * better demonstration / tutorial

**Comment by sjsrey** [comment]
I think this would be a good plan for all the packages, not just spaghetti.

**Comment by darribas** [comment]
Agreed, now we have the notebooks infrastructure, it'd be great to give them a polish!

**Comment by jGaboardi** [comment]
Try swapping out current "Notebook last updated" marker with [`watermark`](https://github.com/rasbt/watermark) as suggested in [pysal/pysal/1057](https://github.com/pysal/pysal/issues/1057#issuecomment-555150332)

**Comment by knaaptime** [comment]
somewhat related, i also started [testing the example notebooks](https://github.com/spatialucr/geosnap/blob/e495b9ba4ca851e0874e9fc4215c6746d9937841/.travis.yml#L43) in `geosnap`. I know there was a decision some time ago to stop doing doctests in pysal because they added too much time to the CI suite, but I was thinking one option might be to omit notebook tests for the submodules and the metapackage, but have them run on the notebooks project (i.e. test that the notebooks actually execute, not only that they compile to markdown)

that would mean making sure all the examples use available data, but could be a nice improvement

**Comment by jGaboardi** [comment]
Tie in with #342 for the `v1.4` release (#340)
