### ISSUE TITLE
Release action failing, trying to upload wrong `dist` files...

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#760]
Release action keeps failing saying that [`v1.7.5` already exists](https://github.com/pysal/spaghetti/actions/runs/7682123116/job/20936090142#step:7:39) on PyPI (which it does not, I deleted it). Maybe not the best idea, but what's done is done. Problem is that when attempting to release a different version (tried `v1.7.5post1` and `v1.7.6`), we're still seeing the same failure & message... I must be overlooking something rather obvious, but can't see it.

@martinfleis @knaaptime Any ideas?

* At the [*Checking out the ref* stage](https://github.com/pysal/spaghetti/actions/runs/7682123116/job/20936090142#step:3:118) we are seeing the `v1.7.5.post1` tag
* But then at [`build` step](https://github.com/pysal/spaghetti/actions/runs/7682123116/job/20936090142#step:5:145) we are seeing a version of  `1.7.5`
* Same thing when I tried a `v1.7.6`: correct [tag](https://github.com/pysal/spaghetti/actions/runs/7682027761/job/20935864272#step:3:114); wrong build [version](https://github.com/pysal/spaghetti/actions/runs/7682027761/job/20935864272#step:5:145)

**Comment by martinfleis** [comment]
> PyPI does not allow for a filename to be reused, even once a project has been deleted and recreated. ([source](https://pypi.org/help/#file-name-reuse))

That answers the issue with 1.7.5.

A tag is attached to a commit. Since there were no commits between 1.7.5, 1.7.6 and 1.7.5.post1, all of them are attached to a single commit. When building a version on top of that commit, setuptools_scm has no way figuring out which of those tags did you want to use, so it uses the first one.

To fix this:

- make a commit to main, possibly empty (`git commit --allow-empty -m 'RLS: v1.7.7')`
- tag that commit
- push

**Comment by jGaboardi** [comment]
> That answers the issue with 1.7.5.

Could have sworn I did this before. Guess not though.

Thanks for the fix! Will try that now.

**Comment by jGaboardi** [comment]
Confirmed works. Thanks again @martinfleis !
